package com.iie.st10320489.marene;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import androidx.room.*;


import androidx.appcompat.app.AppCompatActivity;

import com.iie.st10320489.marene.data.database.AppDatabase;
import com.iie.st10320489.marene.data.entities.User;
import com.iie.st10320489.marene.ui.onboarding.OnboardingActivity;
import com.iie.st10320489.marene.ui.onboarding.OnboardingActivity2;

import java.util.List;

public class SignupActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_signup);

        AppDatabase db;
        db = Room.databaseBuilder(getApplicationContext(),
                        AppDatabase.class, "cashoo_database")
                .allowMainThreadQueries()
                .build();

        Button signupButton = findViewById(R.id.signupLoginButton);
        EditText nameEditText = findViewById(R.id.nameEditText);
        EditText surnameEditText = findViewById(R.id.surnameEditText);
        EditText emailEditText = findViewById(R.id.signupEmailEditText);
        EditText passwordEditText = findViewById(R.id.createPasswordEditText);
        EditText confirmPasswordEditText = findViewById(R.id.confirmPasswordEditText);


        signupButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String name = nameEditText.getText().toString();
                String surname = surnameEditText.getText().toString();
                String email = emailEditText.getText().toString();
                String password = passwordEditText.getText().toString();
                String confirmPassword = confirmPasswordEditText.getText().toString();

                if (name.isEmpty() || surname.isEmpty() || email.isEmpty() || password.isEmpty()) {
                    Toast.makeText(SignupActivity.this, "Please fill all fields", Toast.LENGTH_SHORT).show();
                } else if (!password.equals(confirmPassword)) {
                    Toast.makeText(SignupActivity.this, "Passwords do not match!", Toast.LENGTH_SHORT).show();
                } else {
                    User newUser = new User(
                            0, // userId will be autogenerated
                            name,
                            surname,
                            email,
                            password,
                            0.0, // cashoos starting amount
                            true // isActive
                    );

                    db.userDao().insertUserNow(newUser);

                    // Save the email in SharedPreferences for future use
                    SharedPreferences sharedPreferences = getSharedPreferences("UserPreferences", MODE_PRIVATE);
                    SharedPreferences.Editor editor = sharedPreferences.edit();
                    editor.putString("currentUserEmail", newUser.getEmail()); // Save the email
                    editor.putInt("currentUserId", newUser.getUserId()); // Save the userId as well
                    editor.apply(); // Commit the changes

                    Toast.makeText(SignupActivity.this, "Account created!", Toast.LENGTH_SHORT).show();

                    List<User> users = db.userDao().getAllUsersNow();
                    for (User u : users) {
                        System.out.println("User: " + u.getName() + ", Email: " + u.getEmail() + ", UserId: " + u.getUserId());
                    }
                    // Navigate to OnboardingActivity after successful signup
                    Intent intent = new Intent(SignupActivity.this, OnboardingActivity.class);
                    startActivity(intent);
                    finish(); // Close SignupActivity so the user cannot go back


                }
            }

        });



        TextView signInText = findViewById(R.id.signUpText);
        signInText.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(SignupActivity.this, LoginActivity.class));
            }
        });


    }

}
