name: Android UI Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  androidTest:
    name: Run UI Tests
    runs-on: macos-latest  # macOS is required for Android emulators

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build the app
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Create AVD and start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest
