name: Android UI Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  androidTest:
    name: Run Instrumented UI Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build debug and test APKs
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Run instrumented UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34              # Closest stable to your API 35
          target: google_apis        # Compatible with GitHub Actions
          arch: x86
          profile: pixel             # Closest to Pixel 8 Pro
          emulator-options: -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect
          disable-animations: true
          emulator-boot-timeout: 1200
          script: ./gradlew connectedAndroidTest
